[package]
name = "tbd-lifecycle"
version = "0.1.0"
authors = ["Florian Gilcher <florian.gilcher@asquera.de>"]
edition = "2018"

[dependencies]
tbd-key = { path = "../tbd-key" }
tbd-model-wrappers = { path = "../tbd-model-wrappers" }
