cargo-features = [ "edition" ]

[package]
name = "tbd-core"
version = "0.1.0"
authors = ["Florian Gilcher <florian.gilcher@asquera.de>"]
edition = "2018"

[dependencies]
futures-preview = "0.3.0-alpha.5"
